print("Welcome to Kenya")
print("\nKenya is a country in East Africa.")
print("\nKenya is known for its vast landscapes,wildlife and the annual wildebeest migration.")
print("\nKenya gained its independence from the United Kingdom on 12 December 1963.")
print("\nThe first president of Kenya was Jomo Kenyatta, he was in office from 1964 to 1978 and helped to shape the country into what it is today.")
print("\nKenya has 47 different ethnic groups, each with its own unique culture and traditions.")
print("\nThe official languages of Kenya are English and Swahili, but there are also many other local languages spoken throughout the country.")
print("\nKenya is scientifically known for the some of most alkaline, Lake Magadi and Lake Turkana.")
print("\nLake turukana is the largest desert lake in the world and is home to a unique species od the Nile crocodile which adapted to the lakes alkalinity and developed specialized adaptations to survive in the harsh environment.")
print("\nKenya has had a rich history of producing world-class athletes, particularly in long-distance running. Kenyan runners have won numerous Olympic medals and set world records in various track and field events.")
print("\nThe current president of Kenya is William Ruto, who took office in September 2022. He has focused on economic development, infrastructure projects, and social welfare programs during his tenure.")